### ISSUE TITLE
Readme Images

### ISSUE THREAD

**Issue by temefleet** [temefleet/Instanews-App#1]
![desktop](https://user-images.githubusercontent.com/8882336/28546791-cd12e4fc-7080-11e7-9d32-0a456ea9fe01.png)
![mobile](https://user-images.githubusercontent.com/8882336/28546790-cd108630-7080-11e7-8f29-53cfd9a7f111.png)
![tablet](https://user-images.githubusercontent.com/8882336/28546789-cd0cc496-7080-11e7-8f93-2e539717c58c.png)

**Comment by rcass** [comment]
Is this a ticket to yourself to add these images? I think this just needs to be closed?

**Comment by temefleet** [comment]
Whoops. Thanks!

**Comment by rcass** [comment]
No problemo!
